// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package austinapi_db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Preparedness struct {
	ID               int32
	Date             pgtype.Date
	Rating           pgtype.Int4
	CreatedTimestamp pgtype.Timestamp
	UpdatedTimestamp pgtype.Timestamp
}

type Sleep struct {
	ID               int32
	Date             pgtype.Date
	Rating           pgtype.Int4
	CreatedTimestamp pgtype.Timestamp
	UpdatedTimestamp pgtype.Timestamp
	TotalDuration    pgtype.Int8
}

type Spo2 struct {
	ID               int32
	Date             pgtype.Date
	AverageSpo2      pgtype.Float8
	CreatedTimestamp pgtype.Timestamp
	UpdatedTimestamp pgtype.Timestamp
}
