// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package austinapi_db

import (
	"time"
)

type Heartrate struct {
	ID               int32
	Date             time.Time
	High             int32
	Low              int32
	Average          int32
	CreatedTimestamp time.Time
	UpdatedTimestamp time.Time
}

type Preparedness struct {
	ID               int32
	Date             time.Time
	Rating           int32
	CreatedTimestamp time.Time
	UpdatedTimestamp time.Time
}

type Sleep struct {
	ID               int32
	Date             time.Time
	Rating           int32
	TotalDuration    int32
	NumberSleeps     int32
	CreatedTimestamp time.Time
	UpdatedTimestamp time.Time
}

type Spo2 struct {
	ID               int32
	Date             time.Time
	AverageSpo2      float64
	CreatedTimestamp time.Time
	UpdatedTimestamp time.Time
}

type Stress struct {
	ID                 int32
	Date               time.Time
	HighStressDuration int32
	CreatedTimestamp   time.Time
	UpdatedTimestamp   time.Time
}
